name = "zy-yd-ai-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# 在 Cloudflare Dashboard 中配置这些敏感变量
# OPENAI_API_KEY = "your-openai-key"
# DEEPSEEK_API_KEY = "your-deepseek-key"